[build]
builder = "dockerfile"

[deploy]
startCommand = "./bin/thrust ./bin/rails server"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { RAILS_ENV = "production" }
